// (c) +KZ

#ifndef KZTILES_H
#define KZTILES_H

#include <game/mapitems.h>

enum
{
	//Tiles
	TILE_ADMIN = 1,
	TILE_NOAIR,
	TILE_NOFLAG,
	TILE_TEAMRED,
	TILE_TEAMBLUE,
	TILE_BIGHEART,
	TILE_BIGARMOR,
	TILE_RANDOMWEAPON,
	TILE_WATER,
	TILE_FLY,
	TILE_INVISIBLE,
	TILE_MINE,
	TILE_MINE_ACTIVE,
	TILE_5_DAMAGE,
	TILE_GRENADE_LAUNCHER_H,
	TILE_GRENADE_LAUNCHER_D,
	TILE_BALL,
	TILE_BALL_REDGOAL,
	TILE_BALL_BLUEGOAL,
	TILE_BALL_REDSLAM,
	TILE_BALL_BLUESLAM,
	TILE_TEE_KILL,
	TILE_NO_BALL,
	TILE_BALL_ALTSPAWN,
	TILE_BALL_NOTEAMGOAL,
	TILE_BALL_NOTEAMSLAM,
	TILE_SLOWDEATH,
	TILE_HEALTHZONE,
	TILE_ARMORZONE,
	TILE_TEAMRED_DEATH,
	TILE_TEAMBLUE_DEATH,
	TILE_FLAGBALL_REDGOAL,
	TILE_FLAGBALL_BLUEGOAL,
	TILE_FLAGBALL_NOTEAMGOAL,
	TILE_1_DAMAGE,
	TILE_VANILLA_HEART,
	TILE_VANILLA_ARMOR,
	TILE_INVINCIBLE,
	TILE_NO_INVINCIBLE,
	TILE_GODMODE,
	TILE_NO_GODMODE,
	TILE_SPARKLES_ON,
	TILE_SPARKLES_OFF,
	TILE_SIT,
	TILE_WEAPON_TASER,
	TILE_WEAPON_PORTAL_GUN,
	TILE_WEAPON_MINIGUN,
	TILE_PLUS_JUMP,
	TILE_MINUS_JUMP,
	TILE_WEAPON_BLACKHOLE,
	TILE_WEAPON_BLACKHOLE_AMMO,
	TILE_WEAPON_CHARGE_HAMMER,
	TILE_VEHICLE_HELICOPTER,
	TILE_VEHICLE_JET,
	TILE_CONFETTI_ON,
	TILE_CONFETTI_OFF
};

enum
{
	//Weapons
	CUSTOM_WEAPON_START = NUM_WEAPONS,
	WEAPON_TASER = NUM_WEAPONS,
	WEAPON_PORTAL_GUN,
	WEAPON_MINIGUN,
	WEAPON_BLACKHOLE,
	WEAPON_CHARGE_HAMMER,
	NUM_CUSTOM_WEAPONS
};

#endif
