// (c) +KZ

#ifndef KZTILES_H
#define KZTILES_H

enum
{
	//Tiles
	TILE_ADMIN = 1,
	TILE_NOAIR,
	TILE_NOFLAG,
	TILE_TEAMRED,
	TILE_TEAMBLUE,
	TILE_BIGHEART,
	TILE_BIGARMOR,
	TILE_RANDOMWEAPON,
	TILE_WATER,
	TILE_FLY,
	TILE_INVISIBLE,
	TILE_MINE,
	TILE_MINE_ACTIVE,
	TILE_5_DAMAGE,
	TILE_GRENADE_LAUNCHER_H,
	TILE_GRENADE_LAUNCHER_D,
	TILE_BALL,
	TILE_BALL_REDGOAL,
	TILE_BALL_BLUEGOAL,
	TILE_BALL_REDSLAM,
	TILE_BALL_BLUESLAM,
	TILE_TEE_KILL,
	TILE_NO_BALL,
	TILE_BALL_ALTSPAWN,
	TILE_BALL_NOTEAMGOAL,
	TILE_BALL_NOTEAMSLAM,
	TILE_SLOWDEATH,
	TILE_HEALTHZONE,
	TILE_ARMORZONE,
	TILE_TEAMRED_DEATH,
	TILE_TEAMBLUE_DEATH,
	TILE_FLAGBALL_REDGOAL,
	TILE_FLAGBALL_BLUEGOAL,
	TILE_FLAGBALL_NOTEAMGOAL
};

#endif
